name: Build for 3DS on Ubuntu Linux

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm'

    steps:
    - uses: actions/checkout@v2
    - name: Checkout bannertool
      uses: actions/checkout@v2
      with:
        repository: deltabeard/bannertool
        path: ext/bannertool
    - name: Build Bannertool
      run: |
        make -C ${GITHUB_WORKSPACE}/ext/bannertool
        sudo cp ${GITHUB_WORKSPACE}/ext/bannertool/bannertool.elf /usr/bin/bannertool
    - name: Build
      run: make PLATFORM=3DS BUILD=DEBUG -j$(nproc)
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          README.md
          out/*.3dsx
          out/*.3ds
          out/*.elf
          out/*.cia
