name: Build for 3DS and Windows NT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  job_bannertool:
    name: Build bannertool
    runs-on: ubuntu-latest
    steps:
    - name: Checkout bannertool
      uses: actions/checkout@v2
      with:
        repository: deltabeard/bannertool
        
    - name: Build Bannertool
      run: make VERSION_MAJOR=1 VERSION_MINOR=2 VERSION_MICRO=0 CC="gcc -static" CXX="g++ -static"
      
    - name: Upload bannertool binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3ds-buildtools
        path: bannertool.elf

  job_ctrtools:
    name: Build ${{ matrix.prog }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prog: [ctrtool, makerom]
    steps:
    - name: Checkout Project_CTR
      uses: actions/checkout@v2
      with:
        repository: 3DSGuy/Project_CTR
        
    - name: Build ${{ matrix.prog }}
      run: |
        cd ${{ matrix.prog }}
        make CC="gcc -static" CXX="g++ -static" ${{ matrix.makeArgs }}
      
    - name: Upload ${{ matrix.prog }} binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3ds-buildtools
        path: ${{ matrix.prog }}/${{ matrix.prog }}
    
  job_3ds:
    name: Build 3DS-LVGL for 3DS
    runs-on: ubuntu-latest
    needs: [job_bannertool, job_ctrtools]
    container:
      image: 'devkitpro/devkitarm'

    steps:
    - name: Checkout 3ds-lvgl
      uses: actions/checkout@v2
      
    - name: Download 3ds-buildtools artifact
      uses: actions/download-artifact@v2
      with:
        name: 3ds-buildtools
        
    - name: Restore artifact file permissions and install
      run: |
        sudo mv ./bannertool.elf /usr/bin/bannertool
        sudo mv ./makerom /usr/bin/makerom
        sudo mv ./ctrtool /usr/bin/ctrtool
        sudo chmod -R +x /usr/bin/bannertool /usr/bin/makerom /usr/bin/ctrtool
        
    - name: Build
      run: make PLATFORM=3DS BUILD=RELDEBUG
      
    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: 3ds-lvgl-output
        path: |
          README.md
          out/*.3dsx
          out/*.3ds
          out/*.elf
          out/*.cia
          
  job_nt:
    name: Build 3DS-LVGL for Windows NT
    runs-on: windows-latest

    steps:
    - name: Checkout 3ds-lvgl
      uses: actions/checkout@v2
      
    - name: Install GNU Make
      run: choco install make
      
    - name: Build
      run: make PLATFORM=MSVC BUILD=RELEASE
      
    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: 3ds-lvgl-output
        path: |
          out/*.exe
          out/*.dll
