name: C/C++ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL2
      run: sudo apt-get install libsdl2
    - name: Build
      run: make PLATFORM=UNIX BUILD=DEBUG
